config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'boards#index'

  resources :boards do
    resources :comments, only: [:new, :create]
  end

    resource :task, only: [:show, :edit, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { minimum: 2, maximum: 100 }
  validates :title, format: { with: /\A(?!\@)/ }

  validates :content, presence: true
  validates :content, length: { minimum: 5 }
  validates :content, uniqueness: true

  validate :validate_title_and_content_length
  
  has_many :comments, dependent: :destroy
  belongs_to :user


  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  private
  def validate_title_and_content_length
    char_count = self.title.length + self.content.length
    errors.add(:content, '10文字いじょうで！') unless char_count > 10
    

   
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer          not null
#
# Indexes
#
#  index_comments_on_board_id  (board_id)
#
class Comment < ApplicationRecord
    belongs_to :board
    validates :content, presence: true

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id           :integer          not null, primary key
#  birthday     :date
#  gender       :integer
#  introduction :text
#  nickname     :string
#  subscribed   :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :integer          not null
#
# Indexes
#
#  index_tasks_on_user_id  (user_id)
#
class Task < ApplicationRecord
    enum gender: { male: 0, female: 1, other: 2 }
    belongs_to :user
    has_one_attached :avatar



    def age
        return '不明' unless birthday.present?
        years = Time.zone.now.year - birthday.year
        days = Time.zone.now.yday - birthday.yday
    
        if days < 0
          "#{years - 1}歳"
        else
          "#{years}歳"
        end
      end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :boards, dependent: :destroy
         has_one :task, dependent: :destroy

         delegate :birthday, :age, :gender, to: :task, allow_nil: true

         def has_written?(borad)
          boards.exists?(id: board.id)
         end

         def display_name
          task&.nickname || self.email.split('@').first
         end

       

         def prepare_task
          task || build_task
         end

         def avatar_image
          if task&.avatar&.attached?
            task.avatar
          else
            'default-avatar.png'
          end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    def index
        @boards = Board.all
    end
    

    def show
        @comments = @board.comments
    end

    def new
        @board = current_user.boards.build
    end

    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to board_path(@board), notice: '保存'
        else
            flash.now[:error] = '保存失敗'
            render :new
        end
    end

    def edit
        @board = current_user.boards.find(params[:id])
    end

    def update
        @board = current_user.boards.find(params[:id])
        if @board.update(board_params)
            redirect_to board_path(@board), notice: '更新できました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end
    end




    def destroy
        board = current_user.boards.find(params[:id])
        board.destroy!
        redirect_to root_path, notice: '削除に成功しました'
    end



    private
    def board_params
        params.require(:board).permit(:title, :content)
    end

    def set_board
        @board = Board.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        board = Board.find(params[:board_id])
        @commet = board.comments.build
    end


    def create
        board = Board.find(params[:board_id])
        @comment = board.comments.build(comment_params)
        if @comment.save
            redirect_to board_path(board), notice: 'コメント追加'
        else
            flash.now[:error] = '更新できませんでした'
            render :new
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/task_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!

    def show
        @task = current_user.task
    end

    def edit
        @task = current_user.prepare_task
    end

    def update
       @task = current_user.prepare_task
       @task.assign_attributes(task_params)
        if @task.save
            redirect_to task_path, notice: 'プロフィール更新'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end
    end

    private
    def task_params
        params.require(:task).permit(
            :nickname,
            :introduction,
            :gender,
            :birthday,
            :subscribed,
            :avatar
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.haml
= link_to board_path(board) do
  .card
    .card_image
      = image_tag 'eyecatch1.png'
    .card_content
      .card_title
        = board.title
      .card_heart
        = image_tag 'heart.svg'
        %span 23
      .card_detail
        = image_tag 'default-avatar.png'
        %div
          %p= board.author_name
          %p= board.display_created_at

app/views/boards/_form.html.haml
.container
  %ul
    - board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: board, local: true) do |f|
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/boards/_tabs.html.haml
.tabs
  .tabs_item.active
    新着記事一覧
  .tabs_item
    タイムライン

app/views/boards/edit.html.haml
= render 'form', board: @board

app/views/boards/index.html.haml
.container
  = render 'tabs'
  - @boards.each do |board|
    = render 'commons/board', board: board
  = link_to new_board_path do
    .float_btn
      %i.fa.fa-plus

app/views/boards/new.html.haml
= render 'form', board: @board

app/views/boards/show.html.haml
.board
  %h1.board_title= @board.title
  .board_detail
    = image_tag @board.user.avatar_image
    %div
      %p= @board.author_name
      %p= @board.display_created_at
  - if user_signed_in? && current_user.has_written?(@board)
    .board_detail_actions
      .dropdown
        = image_tag 'actions.svg', class: 'dropbtn'
        .dropdown-content.mini
          = link_to '編集する', edit_board_path(@board)
          = link_to '削除する', board_path(@board), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
  .board_content
    = @board.content
  .board_heart
    = image_tag 'heart.svg'

.board
  %h2 コメント一覧
  - @comments.each do |comment|
    .board_comment
      %p= comment.content


.container
  = link_to new_board_comment_path(@article) do
    .btn-secondary
      コメントを追加

app/views/comments/new.html.haml
.container
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @comment, url: board_comments_path(@comment.article), local: true) do |f|
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/commons/_board.html.haml
= link_to board_path(board) do
  .card
    .card_image
      = image_tag 'eyecatch1.png'
    .card_content
      .card_title
        = board.title
      .card_heart
        = image_tag 'heart.svg'
        %span 23
      .card_detail
        = image_tag board.user.avatar_image
        %div
          %p= board.author_name
          %p= board.display_created_at

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Minato
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          = link_to :back do
            = image_tag 'back.svg', class: 'header_back'
        %p.header_pageTitle Boards
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'プロフィール', task_path
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/tasks/edit.html.haml
.container
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @task, url: task_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, 'アバター'
    %div
      = f.file_field :avatar
    %div
      = f.label :nickname, 'ハンドルネーム'
    %div
      = f.text_field :nickname, class: 'text'
    %div
      = f.label :introduction, '自己紹介'
    %div
      = f.text_area :introduction
    %div
      = f.label :gender, '性別'
    %div
      = f.select :gender, Task.genders.map { |k, v| [ I18n.t("enum.genders.#{k}"), k ] }, {}, { class: 'text' }
    %div
      = f.label :birthday, '生年月日'
    %div
      = f.date_field :birthday, class: 'text'
    %div
      = f.label :subscribed, '通知を受け取る'
      = f.check_box :subscribed

    = f.submit '保存', class: 'btn-primary'

app/views/tasks/show.html.haml
.container.taskPage
  .taskPage_user
    .taskPage_user_image
      = image_tag 'default-avatar.png'
    .taskPage_user_basicInfo
      .taskPage_user_name
        .taskPage_user_displayName
          #{current_user.display_name}（#{current_user.age}・#{I18n.t("enum.genders.#{current_user.gender}")}）
        .taskPage_user_actionButton
          = link_to 'Edit', edit_task_path
      .taskPage_user_introduction
        = curret_user.task&.introduction
  
  - current_user.boards.each do |board|
    = render 'commons/board', board: board